CONTIKI_PROJECT = task1_a_group_3 task1_b_group_3 task2_a_group_3 task2_b_group_3 task2_bonus_a_group_3 task2_bonus_b_group_3
all: $(CONTIKI_PROJECT)

CONTIKI = ../..


MAKE_NET = MAKE_NET_NULLNET
include $(CONTIKI)/Makefile.include
